site_name: Seahorse
theme:
  name: material
  logo: assets/seahorse.png
  favicon: assets/seahorse.png
  features:
  - content.code.copy
  - navigation.footer
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://buttons.github.io/buttons.js
plugins:
  - search
  - gen-files:
      scripts:
        - gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/corail-research/seahorse
    - icon: simple/pypi
      link: https://pypi.org/project/seahorse/

copyright: Copyright &copy; 2023 - 2023 CORAIL research group


markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
