name: Publishing

on:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: Actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest and hatch
        run: |
          hatch env run test

  hatch-build:
    name: Building distributions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Building distros
      run: |
        hatch build
    - uses: actions/upload-artifact@v4
      with:
        name: distros
        path: dist/
        
  pypi-publish:
    needs: hatch-build
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/seahorse
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: distros
        path: dist
    - name: Publishing package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
